Modify LogClient to HTTP
allwefantasy/pyjava pull request #22
Opened 2021-08-29 12:44 UTC by hellozepp

2021-08-30 04:41 UTC, AndieHuang approved these changes

2021-08-30 05:14 UTC, hellozepp commented
> Just a minor suggestion.
> We can persist the msg by log way instead of print out. :)
--------------
Glad to get your advice. We need to use `print()` to redirect the stdout stream to scala instead of `log`.
But just output msg seems not good, I can add a log prefix when groupId and log_user exist, let it be in the console.

2021-08-30 05:49 UTC, AndieHuang approved these changes

2021-08-30 08:39 UTC, allwefantasy requested changes

2021-08-30 08:39 UTC, allwefantasy commented on python/pyjava/api/mlsql.py
> +                print("[owner] [{}] [groupId] [{}] __MMMMMM__ {}".format(self.conf['PY_EXECUTE_USER'],
Why print?

2021-08-30 11:18 UTC, hellozepp commented on python/pyjava/api/mlsql.py
> +                print("[owner] [{}] [groupId] [{}] __MMMMMM__ {}".format(self.conf['PY_EXECUTE_USER'],
When 'spark.mlsql.log.driver.url' is empty, it will be output to `PythonWorkerFactory` via print(). It is used for redirect log.

2021-08-30 12:08 UTC, allwefantasy commented on python/pyjava/api/mlsql.py
> +                print("[owner] [{}] [groupId] [{}] __MMMMMM__ {}".format(self.conf['PY_EXECUTE_USER'],
If the user disable driver log server ,the java side will fails also.

2021-08-31 10:46 UTC, allwefantasy approved these changes

2021-08-31 10:52 UTC, ckeys approved these changes
LGTM

2021-09-02 04:39 UTC, ckeys approved these changes

2021-09-02 04:41 UTC, ckeys approved these changes

2021-09-02 04:41 UTC, ckeys commented
LGTM

2021-09-02 08:07 UTC, merged